version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.8.1
    links:
      - dispatcher:dispatcher
    restart: always
  dispatcher:
    image: semtech/mu-dispatcher:latest
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
    restart: always
  db:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    restart: always
  fastboot:
    image: lblod/frontend-relance:latest-fastboot
    links:
      - identifier:backend
    restart: always
  migrations:
    image: semtech/mu-migrations-service:0.6.0
    links:
      - db:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
  cache:
    image: semtech/mu-cache:2.0.1
    links:
      - resource:backend
    restart: always
  resource:
    image: semtech/mu-cl-resources:1.18.0
    links:
      - db:database
    volumes:
      - ./config/resources:/config
    restart: always
  extract-local-businesses-from-url:
    image: lblod/extract-local-businesses-from-url-service:0.3.0
    links:
      - db:database
    restart: always
